class Interests {
  final List<String> interests = [
    '3D printing',
    'Acting',
    'Action figures',
    'Anime',
    'Archery',
    'Art',
    'Astronomy',
    'Baking',
    'Beau',
    'Bird watching',
    'Blogging',
    'Board Games',
    'Calligraphy',
    'Camping',
    'Candle making',
    'Car Racing',
    'Card Games',
    'Chess',
    'Coding',
    'Coffee',
    'Collecting',
    'Comedy',
    'Comics',
    'Cooking',
    'Cosplay',
    'Crab rangoon people',
    'Cycling',
    'Dancing',
    'DIY projects',
    'Drawing',
    'Environmentalism',
    'Fashion',
    'Filmmaking',
    'Fishing',
    'Fitness',
    'Food',
    'Gaming',
    'Gardening',
    'Genealogy',
    'Graphic Novels',
    'Hiking',
    'History',
    'Horses',
    'Hunting',
    'Interior design',
    'Investing',
    'Jewelry',
    'Knitting',
    'Languages',
    'Magic',
    'Makeup',
    'Manga',
    'Martial Arts',
    'Motorcycling',
    'Movies',
    'Music',
    'Nail art',
    'Origami',
    'Painting',
    'Parkour',
    'Pets',
    'Philosophy',
    'Photography',
    'Podcasts',
    'Pottery',
    'Puzzles',
    'Quilting',
    'Reading',
    'Rock climbing',
    'Robotics',
    'Running',
    'Science',
    'Scrapbooking',
    'Scuba diving',
    'Sewing',
    'Singing',
    'Skiing',
    'Snowboarding',
    'Soap carving',
    'Soap making',
    'Sports',
    'Stand-up comedy',
    'Surfing',
    'Technology',
    'Traveling',
    'TV Shows',
    'Virtual reality',
    'Vlogging',
    'Volunteering',
    'Weightlifting',
    'Wine tasting',
    'Woodworking',
    'Writing',
    'Yoga',
  ];

  List<String> getInterests() {
    return interests;
  }
}

class IceBreakers {
  final List<String> icebreakers = [
    "Imagine a penguin sliding into your DM; what would it say?",
    "If you had to teach a penguin a skill, what would it be?",
    "What kind of music do you think would be played at a penguin party?",
    "What would you do if you saw a penguin wearing a beanie in the grocery store?",
    "What would you do if you woke up as a penguin one day?",
    "What accent do you think penguins would have if they can talk?",
    "Penguins love sliding on ice; what's your \"can't-help-myself\" activity?",
    "Imagine President Trump as a penguin.",
    "If you had a pet penguin, what would you name it?",
    "If you were a penguin, how long you lasting?"
        "What's Penging?",
    "How you doing?",
    "This is your day my Peng!"
  ];

  List<String> getIcebreakers() {
    return icebreakers;
  }
}
