class Interests {
  final List<String> interests = [
    '3D printing',
    'Acting',
    'Action figures',
    'Anime',
    'Archery',
    'Art',
    'Astronomy',
    'Baking',
    'Beau',
    'Bird watching',
    'Blogging',
    'Board Games',
    'Calligraphy',
    'Camping',
    'Candle making',
    'Car Racing',
    'Card Games',
    'Chess',
    'Coding',
    'Coffee',
    'Collecting',
    'Comedy',
    'Comics',
    'Cooking',
    'Cosplay',
    'Crab rangoon people',
    'Cycling',
    'Dancing',
    'DIY projects',
    'Drawing',
    'Environmentalism',
    'Fashion',
    'Filmmaking',
    'Fishing',
    'Fitness',
    'Food',
    'Gaming',
    'Gardening',
    'Genealogy',
    'Graphic Novels',
    'Hiking',
    'History',
    'Horses',
    'Hunting',
    'Interior design',
    'Investing',
    'Jewelry',
    'Knitting',
    'Languages',
    'Magic',
    'Makeup',
    'Manga',
    'Martial Arts',
    'Motorcycling',
    'Movies',
    'Music',
    'Nail art',
    'Origami',
    'Painting',
    'Parkour',
    'Pets',
    'Philosophy',
    'Photography',
    'Podcasts',
    'Pottery',
    'Puzzles',
    'Quilting',
    'Reading',
    'Rock climbing',
    'Robotics',
    'Running',
    'Science',
    'Scrapbooking',
    'Scuba diving',
    'Sewing',
    'Singing',
    'Skiing',
    'Snowboarding',
    'Soap carving',
    'Soap making',
    'Sports',
    'Stand-up comedy',
    'Surfing',
    'Technology',
    'Traveling',
    'TV Shows',
    'Virtual reality',
    'Vlogging',
    'Volunteering',
    'Weightlifting',
    'Wine tasting',
    'Woodworking',
    'Writing',
    'Yoga',
  ];

  List<String> getInterests() {
    return interests;
  }
}
